# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  registry: ghcr.io
  repository: reiche-world/traefik-secrets-exporter
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true

traefik:
  existingClaim: "traefik"
  namespace: "kube-system"

cronjob:
  schedule: "*/10 * * * *"
  extract:
    - fqdn: "www.example.com"
      namespace: "www"
