{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "traefik-secrets-exporter.serviceAccountName" . }}
  namespace: {{ .Values.traefik.namespace }}
  labels:
    {{- include "traefik-secrets-exporter.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}

{{- $seen_namespaces := dict }}
{{- $context := . }}
{{- range .Values.cronjob.extract }}
  {{- if not (hasKey $seen_namespaces .namespace) }}
    {{- $_ := set $seen_namespaces .namespace true }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-manager
  namespace: {{ .namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get","create","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-manager-binding
  namespace: {{ .namespace }}
subjects:
  - kind: ServiceAccount
    name: traefik-secret-exporter
    namespace: {{ $context.Values.traefik.namespace }}
roleRef:
  kind: Role
  name: secret-manager
  apiGroup: rbac.authorization.k8s.io

  {{- end }}
{{- end }}
{{- end }}